spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server
---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 3.36.197.135

serverName: blue_server
---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 3.36.197.135

serverName: green_server
---

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#    static-path-pattern: /resource/**
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://3.36.197.135:3306/EasyPos?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: korea12313


server:
  servlet:
    session:
      timeout: 86400

mybatis:
  type-aliases-package: com.example.easypos.Vo, com.example.easypos.VoBasicInformation
  mapper-locations: mapper/**.xml